version: '3.1'

services:

  postgres:
    image: postgres:alpine3.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
